import type { Metadata } from 'next'
import { Inter } from "next/font/google";

import RecoilProvider from "@/recoil/Provider";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-RampartOne",
});

export const metadata: Metadata = {
  title: "HP And EC Demo Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <RecoilProvider>{children}</RecoilProvider>
      </body>
    </html>
  );
}
